<script setup>
import SeactionHeading from '@/components/sections/SeactionHeading.vue'
</script>
<template>
  <div id="tc-box">
    <SeactionHeading head1="Terms & Conditions" head2="Your Trust, Our Commitment" />
    <div id="tc-text">
      <h3>Terms of Service</h3>

      By accessing the GammaVantage website ("the Site"), you agree to be bound by these terms of
      service, all applicable laws, and regulations, and accept responsibility for compliance with
      any relevant local laws. If you disagree with any part of these terms, you are prohibited from
      using or accessing this site. The content on this website is protected by applicable copyright
      and trademark laws.

      <h3>Service License</h3>

      a. Permission is granted to use the materials (information or software) on GammaVantage for
      personal, non-commercial transitory viewing only. This license grants usage rights, but not
      ownership, and under this license you may not: Modify or copy the materials; Use the materials
      for any commercial purposes or public displays (whether commercial or non-commercial); Attempt
      to decompile or reverse engineer any software used on the Site; Remove any copyright or
      proprietary notices from the materials; or Transfer the materials to another person or
      "mirror" the materials on another server. b. This license automatically terminates if you
      violate any restrictions and may be terminated by GammaVantage at any time. Upon termination,
      you must destroy any downloaded materials in your possession, whether electronic or printed.

      <h3>Disclaimer and Warranties</h3>

      The information on the GammaVantage site is provided "as is." GammaVantage makes no
      warranties, either expressed or implied, and disclaims all other warranties, including but not
      limited to implied warranties of merchantability, fitness for a particular purpose, or
      non-infringement of intellectual property. The data provided on the Site is sourced and
      curated using automated algorithms from various sources. The data, including comments and
      opinions generated by these algorithms, is subject to automation errors and limitations of the
      technology used, such as large language models (LLMs). GammaVantage cannot be held responsible
      for the accuracy, reliability, completeness, or timeliness of the data or for any content
      available on the Site. Despite efforts to ensure accuracy, the materials on the Site may
      contain technical, typographical, or other errors. GammaVantage does not guarantee that any
      material is accurate, complete, or current and may make changes to the content at any time
      without notice. However, GammaVantage does not commit to updating the materials regularly.
      GammaVantage does not warrant or make any representations about the accuracy, reliability, or
      results derived from the use of the materials on the website or related to any linked
      websites.

      <h3>Liability for Our Services</h3>

      GAMMAVANTAGE WILL NOT BE RESPONSIBLE FOR ANY LOST PROFITS, REVENUES, OR DATA, OR FOR ANY
      INDIRECT, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE
      SITE. THE TOTAL LIABILITY OF GAMMAVANTAGE UNDER THESE TERMS, INCLUDING FOR ANY IMPLIED
      WARRANTIES, IS LIMITED TO THE AMOUNT YOU PAID US FOR USING OUR SERVICES. IN ALL CASES,
      GAMMAVANTAGE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE RESULTING FROM YOUR USE OF THE SITE OR
      ITS SERVICES.

      <h3>Links</h3>

      GammaVantage has not reviewed all websites linked from the Site and is not responsible for the
      contents of any such linked sites. The inclusion of any link does not imply an endorsement by
      GammaVantage. Use of any linked website is at the user's own risk.

      <h3>Modifications</h3>

      GammaVantage may revise these terms of service at any time without notice. We will update the
      "last updated" date when changes are made. It is your responsibility to periodically review
      these terms and remain informed about updates. By continuing to use this website, you agree to
      the then-current version of these terms of service.

      <h3>Governing Law</h3>

      These terms and conditions are governed by and construed in accordance with the laws of India.
      You irrevocably submit to the exclusive jurisdiction of the courts located in Hyderabad,
      India, for any disputes or claims arising under these terms.

      <h3>Contact Us</h3>

      To resolve a complaint regarding the Site or for further information about its use, please
      contact us at:

      <br />
      <br />
      GammaVantage Plot 46, <br />
      Krishna Nagar Colony 17, <br />
      PG Road, Secunderabad, 500003<br />
      Email: support@gammavantage.com
    </div>
  </div>
</template>


<style scoped>
#tc-text {
  margin: 5px 60px;
  font-family: 'Alef', sans-serif;
  font-weight: 400;
  font-style: normal;
  width: 70%;
  margin-top: 25px;
  animation: slideInFromLeft 1s forwards;
  margin-bottom: 33vh;
}

h3 {
  margin: 5px 0px;
  margin-top: 25px;
  font-family: 'Alef', sans-serif;
  font-weight: 700;
  font-style: normal;
  animation: slideInFromLeft 850ms forwards;
}
@keyframes slideInFromLeft {
  0% {
    transform: translateX(-100%);
    opacity: 0;
  }
  100% {
    transform: translateX(0);
    opacity: 1;
  }
}
@media only screen and (max-width: 768px) {
  /* For mobile phones: */
  #tc-text {
    margin: 5px 40px;
    font-family: 'Alef', sans-serif;
    font-weight: 400;
    font-style: normal;
    width: 84%;
    margin-top: 25px;
    animation: slideInFromLeft 1s forwards;
    margin-bottom: 33vh;
  }
}
</style>